### ISSUE TITLE
Accessibility of parameters

### ISSUE THREAD

**Issue by marcozullich** [shiningxy/ResNet50-HDC-FPN-FasterRCNN#2]
Hello,
The Baidu link provided for the weights seems not to be working (maybe it is inaccessible from certain countries).
Could it be possible for you to provide a mirror on some other platform, such as Google Drive, Dropbox, Mega, OneDrive?

**Comment by shiningxy** [comment]
Dropbox: [https://www.dropbox.com/s/rg7dqkr71bylaey/save_weights.zip?dl=0](https://www.dropbox.com/s/rg7dqkr71bylaey/save_weights.zip?dl=0)

Google Drive: [https://drive.google.com/file/d/1-v7t9nGHauiUbF_o69d0gz52LSry1vSA/view?usp=share_link](https://drive.google.com/file/d/1-v7t9nGHauiUbF_o69d0gz52LSry1vSA/view?usp=share_link)

:thumbsup: If you can't download save_weights.zip in Baidu. Dropbox and Google Drive maybe will work. 

:pray: If you have any code bugs, please feel free for any questions or suggestions to me. 

:smoking: The code and paper have been written a year ago. It maybe not work well.
